name: CI/CD Pipeline

on:
    push:
        branches: [main, dev, feature/*]
    pull_request:
        branches: [main, dev]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            # Backend - Node.js
            - name: Set up Node.js for server
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: server/package-lock.json

            - name: Install backend dependencies
              working-directory: ./server
              run: npm install

            - name: Run backend tests
              working-directory: ./server
              run: npm run test

            # Frontend - Angular
            - name: Set up Node.js for Angular
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: client/package-lock.json

            - name: Install frontend dependencies
              working-directory: ./client
              run: npm install

            - name: Build Angular app
              working-directory: ./client
              run: npm run test
